---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 0:58
---
commonModule = {};
commonModule.constants = {
    admin = "lisi",
    orders = {"iphone", "cup", "notebook"},
    users = {
        {
            name = "zhangsan",
            age = 18,
            gender = "male",
            city = "shanghai",
            address = "yonghe road",
            role = "customer",
            pwd = "123"

        },
        {
            name = "lsi",
            age = 24,
            gender = "male",
            city = "shanghai",
            address = "kaiyuan road",
            role = "admin",
            pwd = "444"
        }
    }
};

local function isAdmin(user)
    return "admin" == user.role;
end

function commonModule.getUser(userName)
    for i, v in ipairs(commonModule.constants.users) do
        if (userName == v.name) then
            return v;
        end
    end
end

function commonModule.getPwd(userName)
    local user = commonModule.getUser(userName);
    if isAdmin(user) then
        return user.pwd;
    end
end

return commonModule;
