---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 1:15
---
--- 这里的参数是文件(文件名可用不用带.lua后缀)相对于working dir的相对路径
local commonModule = require("package/common");
-- The path used by require to search for a Lua loader.
print(package.path);

local userName = "zhangsan";
local zhangsan = commonModule.getUser(userName);
local zhangsanPwd = commonModule.getPwd(userName)

print(userName)
print(zhangsan)
print(zhangsanPwd)





