---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 0:04
---
print("下面是lua的注释")

-- 单行注释
-- pirnt("do not use this line of code");
-- 多行注释
--[[
这是lua中的标准写法,及其解析规则.从规则中可以看出,多行注释不支持嵌套
long comments, which start with two hyphens followed by two opening square brackets and
run until the first occurrence of two consecutive closing square brackets
]]
-- 多行注释的一种trick技巧
--[[
利用了多行注释的定义,这种写法看起来更加友好. 类似于Java中的/****/
而且如果要打开这段注释,仅仅将第一行前面添加一个-既可以,这样前后两行都会被当作单行注释
--]]
---[[
print("这行代码不会被当作注释")
--]]


