---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 19:31
---

local fileName = ngx.req.get_uri_args()["fileName"];
-- ngx.var.limit_rate = 1024*1024
local file, err = io.open(ngx.config.prefix() .. fileName,"r")
if not file then
    ngx.log(ngx.ERR, "open file error:", err)
    ngx.exit(ngx.HTTP_SERVICE_UNAVAILABLE)
end

local data
while true do
    data = file:read(1024)
    if nil == data then
        break
    end
    ngx.print(data)
    ngx.flush(true)
end
file:close()
