---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 0:02
---


greeting("hello world");

function greeting(content)
    print("cjh: " .. content);
end
