---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 0:30
---
-- 与JavaScript类似,lua的array和list是一个概念,是基于table实现的.
--但是array的table index是整型,且index是从1开始的,即lua的数组是1-based

-- 对于没有hole的array(或list),被称为sequence.#运算符仅仅适用于sequence,如果有hole则程序会出bug
function printSequence(sequence)
    for i = 1, #sequence do
        print(sequence[i]);
    end
end

-- pairs不保证顺序
function iterTable(table)
    for k, v in pairs(table) do
        print(k .. " " .. v)
    end
end

-- ipair保证顺序
function iterArray(array)
    for i, v in ipairs(array) do
        print(i .. " " .. v);
    end
end




local array  = {};
for i = 1, 5 do
    array[i] = i*2;
end
-- 使用#运算符来为数组追加元素
array[#array+1] = 100;
printSequence(array);

print("--------------------------------")
-- 制造带hole的array,
local arrayWithHole = {1, 2, 3, 4, 5};
arrayWithHole[100] = 10000;

-- The length operator is unreliable for lists with holes
-- #在计算seq的长度时,从table的key=1开始,当发现value==nil时,就停止计算length
printSequence(arrayWithHole)


print("--------------------------------")
-- table的遍历用pair
iterTable(arrayWithHole);

print("--------------------------------")
-- array/list 的遍历用ipair
iterArray(arrayWithHole);

