---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjh.
--- DateTime: 2021/6/27 0:15
---

-- Lua支持整形和双精度浮点型

-- 当浮点型和整型参与运算时,结果时浮点型
function decimalOperation()
    local a = 12;
    local b = 23.2;
    local c = 23;
    local result = a + b;
    print(result);

    result = a + c;
    print(result);

end

function integerOperation()
    local a = 12;
    local c = 23;
    result = a + c;
    print(result);
end

-- lua除法运算符与数学运算符的效果相同,与java中的不同
-- print(a // b) lua5.3才支持floor division
function modeOperation()
    local a = 13;
    local b = 2;
    print(a / b)
    print(a % b)
end

function roundingOp()
    local result = math.floor(13/2)
    print(result)
end

--decimalOperation();
--integerOperation();
--modeOperation();
roundingOp();